name: default
description: General-purpose profile with comprehensive exclusions for common build artifacts
version: 1.0.0

# Include all files by default
include:
  - "**/*"

# Exclude common patterns
exclude:
  # Version control
  - .git/**
  - .svn/**
  - .hg/**
  
  # Dependencies
  - node_modules/**
  - vendor/**
  - bower_components/**
  - jspm_packages/**
  
  # Build outputs
  - build/**
  - dist/**
  - out/**
  - target/**
  - .next/**
  - .nuxt/**
  
  # IDE and editor files
  - .idea/**
  - .vscode/**
  - .vs/**
  - "*.swp"
  - "*.swo"
  - "*~"
  
  # Cache and temporary
  - .cache/**
  - .tmp/**
  - tmp/**
  - temp/**
  - "*.log"
  - "*.tmp"
  - "*.cache"
  
  # Lock files
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - composer.lock
  - Gemfile.lock
  - Pipfile.lock
  - poetry.lock
  
  # Compiled files
  - "*.pyc"
  - "*.pyo"
  - "*.class"
  - "*.o"
  - "*.obj"
  
  # Executables and libraries
  - "*.exe"
  - "*.dll"
  - "*.so"
  - "*.dylib"
  
  # System files
  - .DS_Store
  - Thumbs.db
  - desktop.ini
  
  # Archives
  - "*.zip"
  - "*.tar"
  - "*.gz"
  - "*.rar"
  - "*.7z"

options:
  respectGitignore: true
  includeHidden: false
  followSymlinks: false
  maxFileSize: 10485760  # 10MB
  maxTotalSize: 104857600  # 100MB
  maxFileCount: 10000

transformers:
  file-loader:
    enabled: true
  markdown:
    enabled: false  # Must be explicitly enabled - not applied automatically to .md files
    options:
      mode: strip
  csv:
    enabled: false  # Must be explicitly enabled - only shows first N rows when enabled
    options:
      maxRows: 10
  binary:
    enabled: true

output:
  format: xml
  includeMetadata: true
  addLineNumbers: false
  prettyPrint: true